language: groovy
jdk:
  - oraclejdk7
env:
  - MAVEN_PROFILE=platform-helios
  - MAVEN_PROFILE=platform-indigo
  - MAVEN_PROFILE=platform-juno
  - MAVEN_PROFILE=platform-kepler
install: mvn install -DskipTests=true -P $MAVEN_PROFILE -B
script: mvn verify -P $MAVEN_PROFILE -B
